# Generated by Django 2.1.7 on 2019-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=64, unique=True, verbose_name='电话号码')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭住址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
