# Generated by Django 2.1.7 on 2019-03-03 10:24

from django.db import migrations, models
import django.db.models.deletion
import my_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='文件名')),
                ('file_size', models.CharField(blank=True, max_length=128, null=True, verbose_name='文件大小')),
                ('file_path', models.FileField(upload_to=my_web.models.upload_to, verbose_name='文件地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.Customer', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '云盘',
                'verbose_name_plural': '云盘',
            },
        ),
    ]
