# Generated by Django 2.1.7 on 2019-03-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0002_cloud_disk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud_disk',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='cloud_disk',
            name='file_size',
        ),
    ]
