# Generated by Django 2.1.7 on 2019-03-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_auto_20190303_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_head', models.CharField(blank=True, max_length=256, null=True)),
                ('log_context', models.TextField(verbose_name='日志内容')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_web.Customer', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
    ]
